# Generated by Django 4.1.4 on 2023-04-23 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('damo', '0002_alter_pacientes_ecg_alter_pacientes_ind_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pacientes',
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
